version: "3.7"

services:


  bot:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    env_file:
      - src/.env
    command: sh -c "poetry run python -m src"
    restart: unless-stopped




